language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    # C++14
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    # Qt 5.9
    - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
    - sudo apt-get update -qq
    
install: 
    # C++14
    - sudo apt-get -y install g++-7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    # Qt 5.9
    - sudo apt-get -y install qt59base qt59declarative qt59quickcontrols libtiff-dev libgomp1 libexiv2-dev libjpeg-dev
    - source /opt/qt59/bin/qt59-env.sh

script:
  - git clone https://github.com/LibRaw/LibRaw.git
  - cd LibRaw
  - git checkout 0.19-stable
  - git apply ../patches/libraw-makefile.patch
  - make -j3 -f Makefile.dist
  - sudo make install -f Makefile.dist
  - cd ..
  - git clone https://github.com/CarVac/librtprocess.git
  - cd librtprocess
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ../..
  - cd filmulator-gui
  - qmake PREFIX=/usr
  - make -j4
  - make INSTALL_ROOT=appdir install ; find appdir/
  - pwd
  - # Dear upstream, please install to more standard locations
  - mkdir -p appdir/usr/bin ; mv appdir/usr/lib/filmulator-gui/filmulator-gui appdir/usr/bin/filmulator-gui
  - mkdir -p appdir/usr/qml ; mv appdir/usr/lib/filmulator-gui/qml/filmulator-gui/* appdir/usr/qml/
  - rm -rf appdir/usr/lib/filmulator-gui/
  - mkdir -p appdir/usr/share/applications/ ; cp filmulator-gui.desktop.in appdir/usr/share/applications/filmulator-gui.desktop
  - sed -i -e 's|^Exec=.*|Exec=filmulator-gui|g' appdir/usr/share/applications/filmulator-gui.desktop
  - mkdir -p appdir/usr/share/icons/hicolor/64x64/apps/
  - cp filmulator-gui64.png appdir/usr/share/icons/hicolor/64x64/apps/filmulator-gui.png
  - find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=. -qmldir=appdir/usr/qml/ -verbose=2
  - ls -l ./appdir/
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=. -qmldir=appdir/usr/qml/ -verbose=2
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - mv ./Filmulator*.AppImage ./Filmulator-Git-x86_64.AppImage
  - curl -F "file=@./Filmulator-Git-x86_64.AppImage" https://file.io
